<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Leave_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get leave by id
     */
    function get_leave($id)
    {
        return $this->db->get_where('leaves',array('id'=>$id))->row_array();
    }

    function get_leave_details($id)
    {
        return $this->db->select("l.*,lt.leaveType")
        ->join("leave_type lt", "lt.id =  l.LeaveType","left")
       ->get_where('leaves l',array('l.id'=>$id))->row_array();
    }
        
    /*
     * Get all leaves
     */
    function get_all_leaves()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('leaves')->result_array();
    }
    function get_all_leaves_with_type($id=null)
    {
        return $this->db->select("l.*,lt.leaveType,e.empId,e.empName,e.email")
        ->join("leave_type lt", "lt.id =  l.LeaveType","left")
        ->join("users u", "u.id = l.empid","left")
        ->join("employees e", "e.id = u.employee_id","left")
        ->get('leaves l')
        ->result_array();
    }

    function get_leaves_by_user($empId)
    {
        return $this->db->select("l.*,lt.leaveType,e.empId,e.empName,e.email")
                        ->join("leave_type lt", "lt.id =  l.LeaveType")
                        ->join("users u", "u.id = l.empid")
                        ->join("employees e", "e.id = u.employee_id")
                        ->where("l.empid",$empId)
                        ->get('leaves l')
                        ->result_array();

                        
    }
        
    /*
     * function to add new leave
     */
    function add_leave($params)
    {
        $this->db->insert('leaves',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update leave
     */
    function update_leave($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('leaves',$params);
    }

    
    /*
     * function to delete leave
     */
    function delete_leave($id)
    {
        return $this->db->delete('leaves',array('id'=>$id));
    }
}
